# Generated by Django 3.2 on 2026-07-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, null=True, unique=True)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_iniciacion', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('porcentaje', models.IntegerField()),
                ('participantes', models.CharField(max_length=255, null=True)),
                ('puntos', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cupones')),
                ('tipo_categoria', models.CharField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'api_cupon',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, null=True, unique=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_iniciacion', models.DateTimeField(null=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('porcentaje', models.IntegerField()),
                ('participantes', models.CharField(max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='promociones')),
                ('tipo_categoria', models.CharField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'api_promocion',
            },
        ),
        migrations.CreateModel(
            name='PromocionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categoria')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promocion')),
            ],
            options={
                'db_table': 'api_promocioncategoria',
            },
        ),
        migrations.CreateModel(
            name='CuponCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categoria')),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.cupon')),
            ],
            options={
                'db_table': 'api_cuponcategoria',
            },
        ),
        migrations.CreateModel(
            name='Cupon_Aplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('estado', models.BooleanField(default=True)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.cupon')),
            ],
            options={
                'db_table': 'api_cupon_aplicado',
            },
        ),
    ]
