# Generated by Django 3.2 on 2026-07-30 20:37

from django.db import migrations, models


def limpiar_fechas_inventadas(apps, schema_editor):
    """Al agregar un `auto_now_add`, Django rellena las filas existentes con el
    instante de correr la migración. Para los canjes anteriores eso es un dato
    falso — y esta fecha se muestra en la pantalla de auditoría del admin. Se
    dejan en NULL, que es la verdad: no se sabe cuándo se canjearon.

    Corre inmediatamente después del AddField, así que no puede pisar canjes
    nuevos.
    """
    Cupon_Aplicado = apps.get_model('promotions', 'Cupon_Aplicado')
    Cupon_Aplicado.objects.update(fecha_canje=None)


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupon_aplicado',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='cupon_aplicado',
            name='fecha_canje',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cupon_aplicado',
            name='fecha_uso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(limpiar_fechas_inventadas, migrations.RunPython.noop),
    ]
