# Generated by Django 3.2 on 2026-07-30 21:14

from django.db import migrations


# Elimina la feature de promociones. No aplicaba descuentos en ningún flujo de
# pago: solo servía de anuncio. Los datos (30 promociones y el vínculo con 58
# pagos en efectivo) quedaron volcados en
# ViveFacilBack/respaldos/promociones_antes_de_eliminar.json antes de correr esto.
#
# Los pagos NO se borran: RemoveField solo quita la columna promocion_id, las
# filas siguen intactas. Por eso esta migración depende de payments.0008, que
# quita los FK primero — al revés, MySQL rechazaría el DROP de la tabla.
class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_quitar_fk_promocion'),
        ('promotions', '0002_cupon_aplicado_fechas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocioncategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='promocioncategoria',
            name='promocion',
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.DeleteModel(
            name='PromocionCategoria',
        ),
    ]
