# Generated by Django 3.2 on 2026-08-06 19:57
# Reordenado a mano: agrega la FK, migra los datos de tipo_categoria (nombre)
# a categoria_id por coincidencia de nombre, y recién ahí borra la columna
# vieja. El orden generado por makemigrations borraba tipo_categoria antes de
# poder leerla.

from django.db import migrations, models
import django.db.models.deletion


def migrar_nombre_a_fk(apps, schema_editor):
    Cupon = apps.get_model('promotions', 'Cupon')
    Categoria = apps.get_model('catalog', 'Categoria')
    for cupon in Cupon.objects.exclude(tipo_categoria__isnull=True).exclude(tipo_categoria=''):
        categoria = Categoria.objects.filter(nombre=cupon.tipo_categoria).first()
        if categoria:
            cupon.categoria_id = categoria.id
            cupon.save(update_fields=['categoria'])


def revertir_fk_a_nombre(apps, schema_editor):
    Cupon = apps.get_model('promotions', 'Cupon')
    for cupon in Cupon.objects.exclude(categoria__isnull=True):
        cupon.tipo_categoria = cupon.categoria.nombre
        cupon.save(update_fields=['tipo_categoria'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_categoria_pk_int'),
        ('promotions', '0003_eliminar_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones', to='catalog.categoria'),
        ),
        migrations.RunPython(migrar_nombre_a_fk, revertir_fk_a_nombre),
        migrations.RemoveField(
            model_name='cupon',
            name='tipo_categoria',
        ),
    ]
