# Generated by Django 3.2 on 2026-07-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_auto_20260707_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_banco',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('numero_cuenta', models.CharField(default='0999999999', max_length=25)),
            ],
            options={
                'db_table': 'api_cuenta',
            },
        ),
        migrations.CreateModel(
            name='PagoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0.0)),
                ('oferta', models.FloatField(default=0.0)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('concepto', models.CharField(default='Solicitud', max_length=255, null=True)),
                ('referencia', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('proveedor', models.CharField(default='', max_length=255)),
                ('servicio', models.CharField(default='', max_length=255)),
                ('usuario', models.CharField(default='', max_length=255)),
                ('prov_correo', models.CharField(default='', max_length=255)),
                ('prov_telefono', models.CharField(default='0999999999', max_length=15)),
                ('user_telefono', models.CharField(default='0999999999', max_length=15)),
            ],
            options={
                'db_table': 'api_pagoefectivo',
            },
        ),
        migrations.CreateModel(
            name='PagoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_pagosolicitud',
            },
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0.0)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('impuesto', models.IntegerField()),
                ('referencia', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('carrier_id', models.CharField(max_length=255, null=True)),
                ('concepto', models.CharField(default='Solicitud', max_length=255, null=True)),
                ('carrier_code', models.CharField(max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('pago_proveedor', models.BooleanField(default=False)),
                ('cargo_paymentez', models.FloatField(default=0.0)),
                ('cargo_banco', models.FloatField(default=0.0)),
                ('cargo_sistema', models.FloatField(default=0.0)),
                ('proveedor', models.CharField(default='', max_length=255)),
                ('prov_correo', models.CharField(default='', max_length=255)),
                ('prov_telefono', models.CharField(default='0999999999', max_length=15)),
                ('servicio', models.CharField(default='', max_length=255)),
                ('usuario', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'api_pagotarjeta',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='planes')),
                ('duracion', models.IntegerField(default=0)),
                ('precio', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_plan',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_tipo_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=400)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('cvv', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('titular', models.CharField(max_length=400)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('numero', models.BigIntegerField()),
                ('brand', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('token', models.CharField(max_length=400, null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitante')),
            ],
            options={
                'db_table': 'api_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='PlanProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('planProveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.plan')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
            ],
            options={
                'db_table': 'api_planproveedor',
            },
        ),
    ]
