# Generated by Django 3.2 on 2026-07-07 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20260707_1802'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotarjeta',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.cupon'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.promocion'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.solicitud'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='tarjeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.tarjeta'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagosolicitud',
            name='pago_efectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.pagoefectivo'),
        ),
        migrations.AddField(
            model_name='pagosolicitud',
            name='pago_tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.pagotarjeta'),
        ),
        migrations.AddField(
            model_name='pagosolicitud',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.solicitud'),
        ),
        migrations.AddField(
            model_name='pagoefectivo',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.cupon'),
        ),
        migrations.AddField(
            model_name='pagoefectivo',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.promocion'),
        ),
        migrations.AddField(
            model_name='pagoefectivo',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.solicitud'),
        ),
        migrations.AddField(
            model_name='pagoefectivo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.banco'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.tipo_cuenta'),
        ),
    ]
