# Generated by Django 3.2 on 2026-07-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoefectivo',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud'),
        ),
        migrations.AlterField(
            model_name='pagosolicitud',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud'),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud'),
        ),
    ]
