# Generated by Django 3.2 on 2026-07-07 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0003_auto_20260707_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.proveedor'),
        ),
        migrations.AlterField(
            model_name='planproveedor',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.proveedor'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.solicitante'),
        ),
    ]
