# Generated by Django 3.2 on 2026-07-30 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_cupon_aplicado_fechas'),
        ('payments', '0006_pagos_desglose_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoefectivo',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.cupon'),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.cupon'),
        ),
    ]
