# Generated by Django 3.2 on 2026-07-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_cupon_set_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoefectivo',
            name='promocion',
        ),
        migrations.RemoveField(
            model_name='pagotarjeta',
            name='promocion',
        ),
    ]
