# Generated by Django 3.2 on 2026-07-08 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0004_auto_20260707_1831'),
        ('solicitudes', '0002_auto_20260707_1831'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPaymentez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Paymentez', help_text='Nombre descriptivo de esta configuración.', max_length=100)),
                ('app_code_client', models.CharField(max_length=255)),
                ('app_key_client', models.CharField(max_length=255)),
                ('app_code_server', models.CharField(max_length=255)),
                ('app_key_server', models.CharField(max_length=255)),
                ('url_base', models.CharField(default='https://ccapi-stg.paymentez.com/v2/', help_text="Debe terminar en '/'. Ej: https://ccapi-stg.paymentez.com/v2/", max_length=255)),
                ('ambiente', models.CharField(choices=[('stg', 'Staging'), ('prod', 'Producción')], default='stg', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Solo una configuración debe estar activa a la vez.')),
                ('eliminar_tarjeta_tras_compra', models.BooleanField(default=False, help_text='Si está activo, la tarjeta usada se elimina de Paymentez al finalizar la compra (tarjetas de un solo uso). Desactívalo para permitir tarjetas guardadas (caso ViveFacil).')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Paymentez',
                'verbose_name_plural': 'Configuraciones Paymentez',
                'db_table': 'pagos_configuracion_paymentez',
            },
        ),
        migrations.CreateModel(
            name='TransaccionPaymentez',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('datos_facturacion', models.JSONField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia_dev', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('bin', models.CharField(blank=True, max_length=10, null=True)),
                ('card_token', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('estado_paymentez', models.CharField(blank=True, max_length=50, null=True)),
                ('status_detail', models.IntegerField(blank=True, null=True)),
                ('threeds_ctx', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('threeds_data', models.JSONField(blank=True, null=True)),
                ('respuesta_cruda', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pago_tarjeta', models.ForeignKey(blank=True, db_constraint=False, help_text='Se enlaza cuando el pago se aprueba.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_paymentez', to='payments.pagotarjeta')),
                ('solicitud', models.ForeignKey(blank=True, db_constraint=False, help_text='Qué se está pagando.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_paymentez', to='solicitudes.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_paymentez', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción Paymentez',
                'verbose_name_plural': 'Transacciones Paymentez',
                'db_table': 'pagos_transaccion_paymentez',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='transaccionpaymentez',
            index=models.Index(fields=['referencia'], name='pagos_trans_referen_159685_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionpaymentez',
            index=models.Index(fields=['threeds_ctx'], name='pagos_trans_threeds_23f8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionpaymentez',
            index=models.Index(fields=['estado'], name='pagos_trans_estado_35bbc6_idx'),
        ),
    ]
