# Generated by Django 3.2 on 2026-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_seed_config_stg'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionpaymentez',
            name='base_imponible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaccionpaymentez',
            name='iva_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaccionpaymentez',
            name='iva_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
