# Generated by Django 3.2 on 2026-07-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20260706_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.RemoveField(
            model_name='clientexmedalla',
            name='medalla',
        ),
        migrations.RemoveField(
            model_name='clientexmedalla',
            name='user',
        ),
        migrations.DeleteModel(
            name='Insignia',
        ),
        migrations.DeleteModel(
            name='Politicas',
        ),
        migrations.DeleteModel(
            name='Publicidad',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='clientexmedalla',
        ),
        migrations.DeleteModel(
            name='Medalla',
        ),
    ]
