# Generated by Django 3.2 on 2026-07-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20260707_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Ciudad_Disponible',
        ),
        migrations.RemoveField(
            model_name='profesion',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='profesion_proveedor',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='profesion_proveedor',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='solicitudprofesion',
            name='proveedor',
        ),
    ]
