# Generated by Django 3.2 on 2026-07-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20260707_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificacionMasiva',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
