# Generated by Django 3.2 on 2026-07-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20260707_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='tipo_pago',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='ubicacion',
        ),
        migrations.DeleteModel(
            name='Envio_Interesados',
        ),
    ]
