# Generated by Django 3.2 on 2026-07-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20260707_1826'),
        ('payments', '0003_auto_20260707_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
        migrations.DeleteModel(
            name='Tipo_Pago',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
