# Generated by Django 3.2 on 2026-07-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20260707_1831'),
        ('payments', '0004_auto_20260707_1831'),
        ('solicitudes', '0002_auto_20260707_1831'),
        ('api', '0009_auto_20260707_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='user_datos',
        ),
        migrations.DeleteModel(
            name='Cardauth',
        ),
        migrations.RemoveField(
            model_name='codigos',
            name='user_datos',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='document',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='user_datos',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='documentsPendientes',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='user_datos',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Codigos',
        ),
        migrations.DeleteModel(
            name='Datos',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='PendienteDocuments',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor_Pendiente',
        ),
        migrations.DeleteModel(
            name='Solicitante',
        ),
    ]
