# Generated by Django 3.1.14 on 2023-04-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_proveedor_pendiente_foto'),
    ]

    operations = [

    ]
