# Generated by Django 3.2.25 on 2025-07-09 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0187_auto_20230412_2227'),
    ]

    operations = [
        
    ]
