"""
Django settings for TomeSoft_1 project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import sys
# ponytail: PythonAnywhere bufferea stdout — los print() de debug pueden
# quedarse en el buffer y no aparecer en el error log hasta que se llene o
# el proceso se reinicie. Con esto, cada print() se vuelca de inmediato.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)

import pymysql
pymysql.install_as_MySQLdb()

import os
import environ
# import firebase_admin #Kevin
# from firebase_admin import credentials #Kevin
import firebase_admin
from firebase_admin import credentials

from google.auth.transport.requests import Request
from google.oauth2 import service_account


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

FIREBASE_ACCESS_TOKEN = None
ACCESS_URL = "https://fcm.googleapis.com/v1/projects/vive-facil-66ae4/messages:send"
CRED_PATH = os.path.join(BASE_DIR, env('FIREBASE_CREDENTIALS_PATH', default='TomeSoft_1/vive-facil-66ae4-firebase-adminsdk-fo42r-94d590fc9a.json'))
try:
    # Ruta al archivo de credenciales
    cred = credentials.Certificate(CRED_PATH)

    # Inicializa Firebase Admin SDK
    firebase_admin.initialize_app(cred)
    print("Firebase Admin SDK inicializado correctamente.")

    # Generar el token de acceso utilizando google-auth
    credentials = service_account.Credentials.from_service_account_file(
        CRED_PATH,
        scopes=["https://www.googleapis.com/auth/firebase.messaging"]
    )

    # Solicitar un token de acceso
    credentials.refresh(Request())

    # Obtener el token de acceso
    FIREBASE_ACCESS_TOKEN = credentials.token
    print(f"Token de acceso de Firebase obtenido correctamente")
except Exception as e:
    print(f"Error al inicializar Firebase Admin SDK o al obtener el token de acceso: {e}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [
        'tomesoft1.pythonanywhere.com',
        '127.0.0.1',
        'http://localhost:3000/',
        'capacitor://localhost',
        'ccapi-stg.paymentez.com',
        '*'
        ]

CSRF_TRUSTED_ORIGINS = ['tomesoft1.pythonanywhere.com']

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True

#CORS_ALLOW_HEADERS = ['*']
from requests.sessions import default_headers

CORS_ALLOW_HEADERS = list(default_headers()) + [
    'Authorization',
    'Content-Type',
    'X-Requested-With',
    'versionamiento',
    'ngrok-skip-browser-warning',  # ← esto
    'X-CSRFToken',  # ViveFacil_Solicitante2022/Provedor2022 lo mandan a mano en postTokenNotification()
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_inlinecss',
    'dj_rest_auth',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'rest_framework',
    'rest_framework.authtoken',
    'fcm_django',
    # 'api' ya no tiene vistas ni URLs propias de negocio, salvo la ruta
    # irreducible `static/` y utilidades compartidas (Firebase push,
    # FormatEmail) importadas por los `services.py` de las apps de dominio.
    # Sigue registrada acá porque los modelos (`api/models.py`) siguen
    # viviendo físicamente en esta app.
    'api',
    'core',
    'accounts',
    'catalog',
    'solicitudes',
    'payments',
    'pagos',
    'promotions',
    'notifications',
    'content',
]

INSTALLED_APPS += ('naomi',)


REST_FRAMEWORK ={
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.TokenAuthentication',
        ],
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 3,
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    }

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

#FCM_DJANGO_SETTINGS = {
         # default: _('FCM Django')
 #       "APP_VERBOSE_NAME": "ToMe",
         # Your firebase API KEY
  #      "FCM_SERVER_KEY": "AAAANlvtPYk:APA91bHePBAcH81qKtDdJDaajXqbq6bQ2nsnalFr06fuLe9X7s9v3QMy1JEm7bEUChMS0ADF54Z8wH3drHLe6jbDNbAV9jVnqSDCHL41e50HhROqL-pWL2VztQ08TRpw6oaFBwxnbMsS",
         # true if you want to have only one active device per registered user at a time
         # default: False
   #     "ONE_DEVICE_PER_USER": True,
         # devices to which notifications cannot be sent,
         # are deleted upon receiving error response from FCM
         # default: False
    #    "DELETE_INACTIVE_DEVICES": False,
#}

FCM_DJANGO_SETTINGS = {
     # an instance of firebase_admin.App to be used as default for all fcm-django requests
     # default: None (the default Firebase app)
    "DEFAULT_FIREBASE_APP": None,
     # default: _('FCM Django')
    "APP_VERBOSE_NAME": "ToMe",
     # true if you want to have only one active device per registered user at a time
     # default: False
    "ONE_DEVICE_PER_USER": True,
     # devices to which notifications cannot be sent,
     # are deleted upon receiving error response from FCM
     # default: False
    "DELETE_INACTIVE_DEVICES": False,
    "FCM_API_KEY": None,
}

MIDDLEWARE = [

    'core.middleware.RequestIdMiddleware',
    'core.middleware.AccessLogMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'api.versionamiento.VersionamientoMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SITE_ID = 1

ROOT_URLCONF = 'TomeSoft_1.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'TomeSoft_1.wsgi.application'

AUTHENTICATION_BACKENDS = {
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'

    }


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.' + env('DB_ENGINE', default='mysql'),
        'NAME': env('DB_NAME', default='vivefacil'),
        'USER': env('DB_USER', default='root'),
        'PASSWORD': env('DB_PASSWORD', default='root'),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env('DB_PORT', default='3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SOCIALACCOUNT_PROVIDERS = \
    {'facebook':
       {'METHOD': 'oauth2',
        'SCOPE': ['email','public_profile', 'user_friends'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time'],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'kr_KR',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.4'}
        }


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = None
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='info.vivefacile@gmail.com')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static') # Ruta absoluta donde se recopilarán los archivos estáticos
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]
ACCOUNT_EMAIL_VERIFICATION='none'
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_AUTHENTICATION_METHOD='username'

# Paymentez: las credenciales viven en el modelo `pagos.ConfiguracionPaymentez`
# (admin, server-side). Ya NO se leen de settings/.env por seguridad.
# Solo se conserva el host público del backend para construir el term_url de 3DS.
URL_BACKEND_HOST = env('URL_BACKEND_HOST', default='https://tomesoft1.pythonanywhere.com')

# Portado de cemedip/backend: logging estructurado a stdout (con
# sys.stdout.reconfigure(line_buffering=True) más arriba, esto llega sin
# demora al error log de PythonAnywhere) en vez de print() sueltos. En DEBUG
# usa el formatter legible/coloreado; en producción, JSON por línea para
# poder grep-earlo o parsearlo. RequestIdMiddleware/AccessLogMiddleware
# (arriba en MIDDLEWARE) alimentan el request_id y el log de accesos.
LOG_LEVEL = env('LOG_LEVEL', default='INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'core.logging_context.RequestIdFilter',
        },
    },
    'formatters': {
        'console': {
            '()': 'core.logging_context.PrettyConsoleFormatter' if DEBUG else 'core.logging_context.ExtrasJsonFormatter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'console',
            'filters': ['request_id'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
""" 
if DEBUG and False:  #si estas en modo desarrollo elimina la condicion 'and False'
    EMAIL_BACKEND = "naomi.mail.backends.naomi.NaomiBackend"
    EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'tmp')
 """