from django.urls import path

from accounts.api.solicitante.views import (
    CambioContraseniaSolicitanteView,
    CambioPasswordCodigoSolicitanteView,
    CanjearInvitacionSolicitanteView,
    CompleteDataUserSolicitanteView,
    DatosUsuarioSolicitanteView,
    DatoSolicitanteView,
    DispositivoNotificacionSolicitanteView,
    ExisteEmailSolicitanteView,
    FacebookLoginSolicitanteView,
    GoogleLoginSolicitanteView,
    LoginSolicitanteView,
    PuntosSolicitanteView,
    RecuperarPasswordSolicitanteView,
    RegistroRedesSolicitanteView,
    RegistroSolicitanteView,
    SolicitanteUserSolicitanteView,
    ValidarCodigoSolicitanteView,
    VerificarProveedorSolicitanteView,
    VersionAndroidSolicitanteView,
    VersionIosSolicitanteView,
)

urlpatterns = [
    path("login/", LoginSolicitanteView.as_view()),
    path("registro/", RegistroSolicitanteView.as_view()),
    path("login-social/facebook/", FacebookLoginSolicitanteView.as_view()),
    path("login-social/google/", GoogleLoginSolicitanteView.as_view()),
    path("cambiocontrasenia/", CambioContraseniaSolicitanteView.as_view()),
    path("dispositivos-notificacion/", DispositivoNotificacionSolicitanteView.as_view()),
    path("dispositivos-notificacion/token/", DispositivoNotificacionSolicitanteView.as_view()),
    path("datos/", DatoSolicitanteView.as_view()),
    path("redes/<str:user>/", RegistroRedesSolicitanteView.as_view()),
    path("perfil/", SolicitanteUserSolicitanteView.as_view()),
    path("existe-email/<str:email>/", ExisteEmailSolicitanteView.as_view()),
    path("dato-usuario/<str:id>", DatosUsuarioSolicitanteView.as_view()),
    path("completar-datos/<str:username>/", CompleteDataUserSolicitanteView.as_view()),
    path("recuperar-password/<str:user_email>", RecuperarPasswordSolicitanteView.as_view()),
    path("validar-codigo/<str:email>/<str:codigo>", ValidarCodigoSolicitanteView.as_view()),
    path("cambiar-password-codigo/<str:email>/<str:password>/<str:codigo>", CambioPasswordCodigoSolicitanteView.as_view()),
    path("puntos/", PuntosSolicitanteView.as_view()),
    path("invitacion/canjear/", CanjearInvitacionSolicitanteView.as_view()),
    path("verificar-proveedor/", VerificarProveedorSolicitanteView.as_view()),
    path("version/android/", VersionAndroidSolicitanteView.as_view()),
    path("version/ios/", VersionIosSolicitanteView.as_view()),
]
