# Generated by Django 3.2 on 2026-07-07 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardauth',
            fields=[
                ('id_cardauth', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=20)),
                ('auth', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'api_cardauth',
            },
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, null=True)),
                ('apellidos', models.CharField(max_length=255, null=True)),
                ('ciudad', models.CharField(max_length=20, null=True)),
                ('cedula', models.CharField(default='0999999999', max_length=20, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_perfil')),
                ('estado', models.BooleanField(default=True)),
                ('security_access', models.UUIDField(blank=True, editable=False, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('puntos', models.PositiveIntegerField(default=0, null=True)),
                ('codigo_invitacion', models.CharField(default='', max_length=12, null=True)),
                ('dinero_invertido', models.PositiveIntegerField(default=0, null=True)),
                ('tramites', models.PositiveIntegerField(default=0, null=True)),
                ('descuento', models.PositiveIntegerField(default=0, null=True)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_datos',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('documento', models.FileField(null=True, upload_to='documents')),
                ('estado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_document',
            },
        ),
        migrations.CreateModel(
            name='PendienteDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='pendientes-documents')),
            ],
            options={
                'db_table': 'api_pendientedocuments',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_registro_completo', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('user_datos', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.datos')),
            ],
            options={
                'db_table': 'api_solicitante',
            },
        ),
        migrations.CreateModel(
            name='Proveedor_Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=255)),
                ('apellidos', models.CharField(default='', max_length=255)),
                ('ciudad', models.CharField(default='', max_length=255)),
                ('direccion', models.CharField(default='', max_length=300)),
                ('genero', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(default='', max_length=255)),
                ('copiaCedula', models.FileField(null=True, upload_to='pendientes-copias')),
                ('telefono', models.CharField(default='', max_length=255)),
                ('descripcion', models.TextField()),
                ('cedula', models.CharField(default='', max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('profesion', models.CharField(default='', max_length=255)),
                ('licencia', models.CharField(default='', max_length=55)),
                ('copiaLicencia', models.FileField(null=True, upload_to='pendientes-copias')),
                ('ano_experiencia', models.PositiveIntegerField(default=0)),
                ('banco', models.CharField(default='', max_length=255)),
                ('numero_cuenta', models.CharField(default='', max_length=25)),
                ('rechazo', models.CharField(default='', max_length=255, null=True)),
                ('tipo_cuenta', models.CharField(default='', max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_proveedor')),
                ('documentsPendientes', models.ManyToManyField(db_table='api_proveedor_pendiente_documentspendientes', to='accounts.PendienteDocuments')),
            ],
            options={
                'db_table': 'api_proveedor_pendiente',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=4.0)),
                ('servicios', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('profesion', models.CharField(default='', max_length=400)),
                ('copiaCedula', models.FileField(blank=True, null=True, upload_to='documentos-Proveedor')),
                ('direccion', models.CharField(default='', max_length=300)),
                ('licencia', models.CharField(default='', max_length=55)),
                ('copiaLicencia', models.FileField(blank=True, null=True, upload_to='documentos-Proveedor')),
                ('ano_profesion', models.CharField(default='', max_length=400)),
                ('banco', models.CharField(default='', max_length=255)),
                ('numero_cuenta', models.CharField(default='', max_length=25)),
                ('tipo_cuenta', models.CharField(default='', max_length=50)),
                ('fecha_caducidad', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('document', models.ManyToManyField(db_table='api_proveedor_document', to='accounts.Document')),
                ('user_datos', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.datos')),
            ],
            options={
                'db_table': 'api_proveedor',
            },
        ),
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_datos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.datos')),
            ],
            options={
                'db_table': 'api_codigos',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('user_datos', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.datos')),
            ],
            options={
                'db_table': 'api_administrador',
            },
        ),
    ]
