# Generated by Django 3.2 on 2026-07-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cardauth',
        ),
    ]
