# Generated by Django 3.2 on 2026-07-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_cardauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='rating',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='total_resenas_dejadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='total_resenas_dejadas_puntos',
            field=models.FloatField(default=0),
        ),
    ]
