# Generated by Django 3.2 on 2026-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260723_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='total_resenas_dejadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='total_resenas_dejadas_puntos',
            field=models.FloatField(default=0),
        ),
    ]
