# Generated by Django 3.2 on 2026-07-27 17:33

import secrets
import string

from django.db import migrations, models
import django.db.models.deletion

ALFABETO = string.ascii_uppercase + string.digits


def backfill_codigos(apps, schema_editor):
    """Asigna un código único de 8 chars a cada Datos sin código, para que la
    constraint unique de codigo_invitacion no choque con los '' preexistentes."""
    Datos = apps.get_model('accounts', 'Datos')
    usados = set(
        Datos.objects.exclude(codigo_invitacion__in=['', None])
        .values_list('codigo_invitacion', flat=True)
    )
    for dato in Datos.objects.filter(models.Q(codigo_invitacion='') | models.Q(codigo_invitacion=None)):
        while True:
            codigo = ''.join(secrets.choice(ALFABETO) for _ in range(8))
            if codigo not in usados:
                usados.add(codigo)
                break
        dato.codigo_invitacion = codigo
        dato.save(update_fields=['codigo_invitacion'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20260723_1209'),
    ]

    operations = [
        # api_datos.id ya es INT en la BD; solo alineamos el estado de Django
        # (el app_config global usa BigAutoField). Sin operación de BD: MODIFY
        # sobre un PK referenciado por muchas FK es innecesario y riesgoso.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='datos',
                    name='id',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
            ],
            database_operations=[],
        ),
        # Backfill de códigos ANTES de imponer unique.
        migrations.RunPython(backfill_codigos, noop),
        migrations.AlterField(
            model_name='datos',
            name='codigo_invitacion',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(default=0)),
                ('motivo', models.CharField(choices=[('medalla', 'Medalla'), ('cupon', 'Cupón'), ('invitacion_recibida', 'Invitación (canje)'), ('invitacion_enviada', 'Invitación (referido)'), ('ajuste_admin', 'Ajuste admin')], max_length=30)),
                ('saldo_resultante', models.PositiveIntegerField(default=0)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_puntos', to='accounts.datos')),
            ],
            options={
                'db_table': 'api_movimiento_puntos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('invitado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitacion_recibida', to='accounts.datos')),
                ('invitador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to='accounts.datos')),
            ],
            options={
                'db_table': 'api_invitacion',
            },
        ),
    ]
