# Generated by Django 3.2 on 2026-07-30 17:17

from django.db import migrations, models
from django.utils.timezone import now
import django.utils.timezone


def rellenar_fechas_nulas(apps, schema_editor):
    """El campo pasa a NOT NULL, así que las filas viejas sin fecha se ponen
    en el momento de correr la migración. Es una aproximación aceptada: no hay
    forma de recuperar la fecha real de esos registros."""
    Datos = apps.get_model('accounts', 'Datos')
    actualizadas = Datos.objects.filter(fecha_creacion__isnull=True).update(fecha_creacion=now())
    if actualizadas:
        print(f"  fecha_creacion rellenada en {actualizadas} fila(s) de api_datos")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20260727_1233'),
    ]

    operations = [
        # El relleno va antes del AlterField: si quedara alguna fila en NULL,
        # MySQL rechaza el cambio a NOT NULL.
        migrations.RunPython(rellenar_fechas_nulas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='datos',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
