# Generated by Django 3.2 on 2026-07-30 17:22

from django.db import migrations, models
from django.db.models import F
import django.utils.timezone


def sembrar_fecha_modificacion(apps, schema_editor):
    """Django rellena las filas existentes con el instante de correr la
    migración, pero hay un valor más fiel: hasta ahora, editar un proveedor
    escribía la fecha de la edición encima de `fecha_creacion`. O sea que ese
    campo ya venía guardando "último toque" en las filas editadas y "alta" en
    el resto. Copiarlo conserva ese dato en el campo correcto.

    Se usa .update() a propósito: salta save() y por lo tanto el auto_now, que
    si no volvería a poner el instante de la migración.
    """
    Datos = apps.get_model('accounts', 'Datos')
    Datos.objects.update(fecha_modificacion=F('fecha_creacion'))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_datos_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(sembrar_fecha_modificacion, migrations.RunPython.noop),
        # editable=False es solo a nivel Python: no genera SQL ni bloquea la tabla.
        migrations.AlterField(
            model_name='datos',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
