from django.urls import path

from payments.api.admin.views import (
    PagosEfectivoAdminView,
    PagosEfectivoFechasAdminView,
    PagosEfectivoPaginadoAdminView,
    PagosSolicitudEfectivoAdminView,
    PagosSolicitudTarjetaAdminView,
    PagosTarjetaAdminView,
    PagosTarjetaFechasAdminView,
    PagosTarjetaPaginadoAdminView,
    PlanesAdminView,
    PlanesEstadoAdminView,
    PlanProveedoresFiltroFechaAdminView,
    PlanProveedorAdminView,
    ProveedoresFiltroFechaYNombreAdminView,
    ValorTotalAdminView,
    ValorTotalBancTarjetaAdminView,
    ValorTotalEfectivoAdminView,
    ValorTotalPayTarjetaAdminView,
    ValorTotalProveedoresAdminView,
    ValorTotalSisTarjetaAdminView,
    ValorTotalTarjetaAdminView,
)

urlpatterns = [
    path("planes/", PlanesAdminView.as_view()),
    path("planes/<str:id>/", PlanesAdminView.as_view()),
    path("planes-estado/", PlanesEstadoAdminView.as_view()),
    path("plan-proveedor/", PlanProveedorAdminView.as_view()),
    path("plan-proveedor/<str:id>/", PlanProveedorAdminView.as_view()),
    path("pagos-efectivo/", PagosEfectivoAdminView.as_view()),
    path("pagos-efectivo/paginado/", PagosEfectivoPaginadoAdminView.as_view()),
    path("pagos-efectivo/fechas/", PagosEfectivoFechasAdminView.as_view()),
    path("pagos-tarjeta/", PagosTarjetaAdminView.as_view()),
    path("pagos-tarjeta/paginado/", PagosTarjetaPaginadoAdminView.as_view()),
    path("pagos-tarjeta/fechas/", PagosTarjetaFechasAdminView.as_view()),
    path("valor-total/efectivo/", ValorTotalEfectivoAdminView.as_view()),
    path("valor-total/tarjeta/", ValorTotalTarjetaAdminView.as_view()),
    path("valor-total/pay-tarjeta/", ValorTotalPayTarjetaAdminView.as_view()),
    path("valor-total/banc-tarjeta/", ValorTotalBancTarjetaAdminView.as_view()),
    path("valor-total/sis-tarjeta/", ValorTotalSisTarjetaAdminView.as_view()),
    path("valor-total/", ValorTotalAdminView.as_view()),
    path("valor-total/proveedores/", ValorTotalProveedoresAdminView.as_view()),
    path("pagos-solicitud/efectivo/<str:pago_ID>/", PagosSolicitudEfectivoAdminView.as_view()),
    path("pagos-solicitud/tarjeta/<str:pago_ID>/", PagosSolicitudTarjetaAdminView.as_view()),
    path("plan-proveedores/fecha/", PlanProveedoresFiltroFechaAdminView.as_view()),
    path("proveedores/fecha-nombre/", ProveedoresFiltroFechaYNombreAdminView.as_view()),
]
