# Generated by Django 3.2 on 2026-07-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_auto_20260707_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='categoria')),
                ('foto2', models.ImageField(upload_to='categoria2')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_categoria',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'api_ciudad',
            },
        ),
        migrations.CreateModel(
            name='Ciudad_Disponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_ciudad_disponible',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('foto', models.ImageField(null=True, upload_to='profesion')),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_profesion',
            },
        ),
        migrations.CreateModel(
            name='SolicitudProfesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=150)),
                ('anio_experiencia', models.PositiveIntegerField(default=0)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('documento', models.FileField(null=True, upload_to='solicitudes')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
            ],
            options={
                'db_table': 'api_solicitudprofesion',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('foto', models.ImageField(null=True, upload_to='servicio')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.categoria')),
            ],
            options={
                'db_table': 'api_servicio',
            },
        ),
        migrations.CreateModel(
            name='Profesion_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_experiencia', models.PositiveIntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('profesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.profesion')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
            ],
            options={
                'db_table': 'api_profesion_proveedor',
            },
        ),
        migrations.AddField(
            model_name='profesion',
            name='servicio',
            field=models.ManyToManyField(db_table='api_profesion_servicio', to='catalog.Servicio'),
        ),
    ]
