# Generated by Django 3.2 on 2026-07-07 23:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_auto_20260707_1826'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_tipo_pago',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=30)),
                ('altitud', models.DecimalField(decimal_places=15, max_digits=30)),
                ('direccion', models.CharField(max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('foto_ubicacion', models.ImageField(blank=True, null=True, upload_to='foto_solicitud/foto_ubicacion')),
            ],
            options={
                'db_table': 'api_ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('foto_descripcion', models.ImageField(blank=True, null=True, upload_to='foto_solicitud/foto_descripcion')),
                ('fecha_expiracion', models.DateTimeField(default=django.utils.timezone.now, max_length=200)),
                ('adjudicar', models.BooleanField(default=False)),
                ('pagada', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('descuento', models.FloatField(default=0.0)),
                ('termino', models.CharField(blank=True, choices=[('finalizado', 'finalizado'), ('cancelado', 'cancelado'), ('pagado', 'pagado')], default=None, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('descripcion_rating', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('rating', models.FloatField(default=0)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.proveedor')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.servicio')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitante')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.tipo_pago')),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.ubicacion')),
            ],
            options={
                'db_table': 'api_solicitud',
            },
        ),
        migrations.CreateModel(
            name='Envio_Interesados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesado', models.BooleanField(default=False)),
                ('oferta', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitudes.solicitud')),
            ],
            options={
                'db_table': 'api_envio_interesados',
            },
        ),
    ]
