# Generated by Django 3.2 on 2026-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20260707_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcion_rating_solicitante',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='rating_solicitante',
            field=models.FloatField(default=0),
        ),
    ]
