# Generated by Django 3.2 on 2026-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_auto_20260723_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio_interesados',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio_interesados',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='envio_interesados',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
    ]
