# Generated by Django 3.2 on 2026-07-07 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('porcentaje', models.FloatField(default=0.0)),
                ('titulo', models.CharField(default=' ', max_length=200)),
            ],
            options={
                'db_table': 'api_cargo',
            },
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('imagen', models.ImageField(blank=True, upload_to='insignias')),
                ('tipo_usuario', models.CharField(default=' ', max_length=25)),
                ('servicio', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('pedidos', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_insignia',
            },
        ),
        migrations.CreateModel(
            name='Medalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='insignias')),
                ('estado', models.BooleanField(default=True)),
                ('tiempo', models.PositiveIntegerField(default=0)),
                ('valor', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('puntos', models.PositiveIntegerField(default=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_medalla',
            },
        ),
        migrations.CreateModel(
            name='Politicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('terminos', models.TextField()),
            ],
            options={
                'db_table': 'api_politicas',
            },
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicidad')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_publicidad',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='suggestion')),
                ('usuario', models.CharField(default='', max_length=255)),
                ('correo', models.CharField(default='', max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_suggestion',
            },
        ),
        migrations.CreateModel(
            name='clientexmedalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuario', models.BooleanField(default=True)),
                ('medalla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.medalla')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_clientexmedalla',
            },
        ),
    ]
