# Generated by Django 3.2 on 2026-07-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('banco', 'Banco'), ('paymentez', 'Paymentez'), ('sistema', 'Sistema')], max_length=20, null=True, unique=True),
        ),
    ]
