# Generated by Django 3.2 on 2026-07-07 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('tipo_proveedores', models.CharField(max_length=100, null=True)),
                ('frecuencia', models.CharField(max_length=100, null=True)),
                ('ruta', models.CharField(max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_iniciacion', models.DateTimeField(null=True)),
                ('fecha_expiracion', models.DateTimeField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='notificaciones-masivas')),
            ],
            options={
                'db_table': 'api_notificacionmasiva',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('tipo_proveedores', models.CharField(max_length=100, null=True)),
                ('frecuencia', models.CharField(max_length=100, null=True)),
                ('ruta', models.CharField(max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_iniciacion', models.DateTimeField(null=True)),
                ('fecha_expiracion', models.DateTimeField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='notificaciones')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_notificacion',
            },
        ),
    ]
